# Generated by Django 2.1.2 on 2018-10-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
